# Generated by Django 4.1.7 on 2023-03-29 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_period',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('batch', models.IntegerField(null=True)),
                ('degree', models.CharField(max_length=100, null=True)),
                ('year', models.CharField(max_length=2, null=True)),
                ('semester', models.CharField(max_length=2, null=True)),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
            ],
            options={
                'unique_together': {('batch', 'degree', 'year', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField(null=True)),
                ('reason', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
            ],
            options={
                'unique_together': {('batch', 'date')},
            },
        ),
        migrations.CreateModel(
            name='enrollment',
            fields=[
                ('enroll', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('courses', models.ManyToManyField(to='course.course_period')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
