# Generated by Django 4.1.2 on 2023-02-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.DateField(null=True, verbose_name='Year')),
                ('degree', models.CharField(max_length=100, null=True)),
                ('year', models.CharField(max_length=2, null=True)),
                ('semester', models.CharField(max_length=2, null=True)),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
    ]
