# Generated by Django 4.1.2 on 2023-02-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidays',
            name='batch',
            field=models.IntegerField(null=True),
        ),
    ]
