# Generated by Django 4.1.2 on 2023-02-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_holidays_batch'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='holidays',
            unique_together={('batch', 'reason', 'date')},
        ),
    ]
