# Generated by Django 4.1.2 on 2023-02-19 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_holidays_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_period',
            name='batch',
            field=models.IntegerField(null=True),
        ),
    ]
