# Generated by Django 4.1.2 on 2023-02-19 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='course_period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.DateField(null=True, verbose_name='Year')),
                ('degree', models.CharField(max_length=100, null=True)),
                ('year', models.CharField(max_length=2, null=True)),
                ('semester', models.CharField(max_length=2, null=True)),
                ('start', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunday_holidays', models.DateField(null=True)),
                ('govt_holidays', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('course_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendence.course_period')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'unique_together': {('user', 'course_period', 'date')},
            },
        ),
    ]
