# Generated by Django 4.1.2 on 2023-02-19 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='holidays',
        ),
        migrations.AlterField(
            model_name='attendence',
            name='course_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course_period'),
        ),
        migrations.DeleteModel(
            name='course_period',
        ),
    ]
