# Generated by Django 4.1.2 on 2023-02-19 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_period_batch'),
        ('accounts', '0002_alter_student_batch'),
        ('attendence', '0003_rename_attendence_attendence_first_year_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='attendence_third_year',
            new_name='attendence_1_year',
        ),
        migrations.RenameModel(
            old_name='attendence_second_year',
            new_name='attendence_2_year',
        ),
        migrations.RenameModel(
            old_name='attendence_first_year',
            new_name='attendence_3_year',
        ),
        migrations.RenameModel(
            old_name='attendence_fourth_year',
            new_name='attendence_4_year',
        ),
    ]
