# Generated by Django 4.1.2 on 2023-02-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_face'),
        ('attendence', '0004_rename_attendence_third_year_attendence_1_year_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendence_1_year',
            unique_together={('user', 'date')},
        ),
        migrations.RemoveField(
            model_name='attendence_1_year',
            name='course_period',
        ),
    ]
