# Generated by Django 4.1.7 on 2023-03-25 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0005_alter_attendence_1_year_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendence_3_year',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attendence_3_year',
            name='course_period',
        ),
        migrations.RemoveField(
            model_name='attendence_3_year',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='attendence_4_year',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='attendence_4_year',
            name='course_period',
        ),
        migrations.RemoveField(
            model_name='attendence_4_year',
            name='user',
        ),
        migrations.DeleteModel(
            name='attendence_2_year',
        ),
        migrations.DeleteModel(
            name='attendence_3_year',
        ),
        migrations.DeleteModel(
            name='attendence_4_year',
        ),
    ]
